// Testimony
export const GET_TESTIMONY_LIST_LOADING = "GET_TESTIMONY_LIST_LOADING";
export const GET_TESTIMONY_LIST_SUCCESS = "GET_TESTIMONY_LIST_SUCCESS";

export const GET_TESTIMONY_LIST_ID_LOADING = "GET_TESTIMONY_LIST_ID_LOADING";
export const GET_TESTIMONY_LIST_ID_SUCCESS = "GET_TESTIMONY_LIST_ID_SUCCESS";
export const GET_TESTIMONY_LIST_ID_ERROR = "GET_TESTIMONY_LIST_ID_ERROR";

export const GET_TESTIMONY_LIST_FILTER_BY = "GET_TESTIMONY_LIST_FILTER_BY";
export const GET_TESTIMONY_LIST_SEARCH_LOADING =
  "GET_TESTIMONY_LIST_SEARCH_LOADING";
export const GET_TESTIMONY_LIST_SEARCH_SUCCESS =
  "GET_TESTIMONY_LIST_SEARCH_SUCCESS";

export const ADD_TESTIMONY_LIST_LOADING = "ADD_TESTIMONY_LIST_LOADING";
export const ADD_TESTIMONY_LIST_SUCCESS = "ADD_TESTIMONY_LIST_SUCCESS";
export const ADD_TESTIMONY_LIST_ERROR = "ADD_TESTIMONY_LIST_ERROR";

export const UPDATE_TESTIMONY_LOADING = "UPDATE_TESTIMONY_LOADING";
export const UPDATE_TESTIMONY_SUCCESS = "UPDATE_TESTIMONY_SUCCESS";
export const UPDATE_TESTIMONY_ERROR = "UPDATE_TESTIMONY_ERROR";

export const DELETE_TESTIMONY_LOADING = "DELETE_TESTIMONY_LOADING";
export const DELETE_TESTIMONY_SUCCESS = "DELETE_TESTIMONY_SUCCESS";
export const DELETE_TESTIMONY_ERROR = "DELETE_TESTIMONY_ERROR";

export const CLEAN_TESTIMONY_STATE = "CLEAN_TESTIMONY_STATE";

// City List
export const GET_CITY_LIST_LOADING = "GET_CITY_LIST_LOADING";
export const GET_CITY_LIST_SUCCESS = "GET_CITY_LIST_SUCCESS";
export const GET_CITY_LIST_ERROR = "GET_CITY_LIST_ERROR";

export const GET_CITY_LIST_ID_LOADING = "GET_CITY_LIST_ID_LOADING";
export const GET_CITY_LIST_ID_SUCCESS = "GET_CITY_LIST_ID_SUCCESS";
export const GET_CITY_LIST_ID_ERROR = "GET_CITY_LIST_ID_ERROR";

export const GET_CITY_LIST_FILTER_BY = "GET_CITY_LIST_FILTER_BY";
export const GET_CITY_LIST_SEARCH_LOADING = "GET_CITY_LIST_SEARCH_LOADING";
export const GET_CITY_LIST_SEARCH_SUCCESS = "GET_CITY_LIST_SEARCH_SUCCESS";

export const ADD_CITY_LIST_LOADING = "ADD_CITY_LIST_LOADING";
export const ADD_CITY_LIST_SUCCESS = "ADD_CITY_LIST_SUCCESS";
export const ADD_CITY_LIST_ERROR = "ADD_CITY_LIST_ERROR";

export const UPDATE_CITY_LOADING = "UPDATE_CITY_LOADING";
export const UPDATE_CITY_SUCCESS = "UPDATE_CITY_SUCCESS";
export const UPDATE_CITY_ERROR = "UPDATE_CITY_ERROR";

export const DELETE_CITY_LOADING = "DELETE_CITY_LOADING";
export const DELETE_CITY_SUCCESS = "DELETE_CITY_SUCCESS";
export const DELETE_CITY_ERROR = "DELETE_CITY_ERROR";

export const CLEAN_CITY_STATE = "CLEAN_CITY_STATE";

// Branch List
export const GET_BRANCH_LIST_LOADING = "GET_BRANCH_LIST_LOADING";
export const GET_BRANCH_LIST_SUCCESS = "GET_BRANCH_LIST_SUCCESS";

export const GET_BRANCH_LIST_ID_LOADING = "GET_BRANCH_LIST_ID_LOADING";
export const GET_BRANCH_LIST_ID_SUCCESS = "GET_BRANCH_LIST_ID_SUCCESS";
export const GET_BRANCH_LIST_ID_ERROR = "GET_BRANCH_LIST_ID_ERROR";

export const GET_BRANCH_LIST_FILTER_BY = "GET_BRANCH_LIST_FILTER_BY";
export const GET_BRANCH_LIST_SEARCH_LOADING = "GET_BRANCH_LIST_SEARCH_LOADING";
export const GET_BRANCH_LIST_SEARCH_SUCCESS = "GET_BRANCH_LIST_SEARCH_SUCCESS";

export const ADD_BRANCH_LIST_LOADING = "ADD_BRANCH_LIST_LOADING";
export const ADD_BRANCH_LIST_SUCCESS = "ADD_BRANCH_LIST_SUCCESS";
export const ADD_BRANCH_LIST_ERROR = "ADD_BRANCH_LIST_ERROR";

export const UPDATE_BRANCH_LOADING = "UPDATE_BRANCH_LOADING";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_ERROR = "UPDATE_BRANCH_ERROR";

export const DELETE_BRANCH_LOADING = "DELETE_BRANCH_LOADING";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_ERROR = "DELETE_BRANCH_ERROR";

export const GET_ALL_BRANCH_LOADING = "GET_ALL_BRANCH_LOADING";
export const GET_ALL_BRANCH_SUCCESS = "GET_ALL_BRANCH_SUCCESS";
export const GET_ALL_BRANCH_ERROR = "GET_ALL_BRANCH_ERROR";

export const CLEAN_BRANCH_STATE = "CLEAN_BRANCH_STATE";

// Salesman List
export const GET_SALESMAN_LIST_LOADING = "GET_SALESMAN_LIST_LOADING";
export const GET_SALESMAN_LIST_SUCCESS = "GET_SALESMAN_LIST_SUCCESS";

export const GET_SALESMAN_LIST_ID_LOADING = "GET_SALESMAN_LIST_ID_LOADING";
export const GET_SALESMAN_LIST_ID_SUCCESS = "GET_SALESMAN_LIST_ID_SUCCESS";
export const GET_SALESMAN_LIST_ID_ERROR = "GET_SALESMAN_LIST_ID_ERROR";

export const GET_SALESMAN_LIST_FILTER_BY = "GET_SALESMAN_LIST_FILTER_BY";
export const GET_SALESMAN_LIST_SEARCH_LOADING =
  "GET_SALESMAN_LIST_SEARCH_LOADING";
export const GET_SALESMAN_LIST_SEARCH_SUCCESS =
  "GET_SALESMAN_LIST_SEARCH_SUCCESS";

export const ADD_SALESMAN_LIST_LOADING = "ADD_SALESMAN_LIST_LOADING";
export const ADD_SALESMAN_LIST_SUCCESS = "ADD_SALESMAN_LIST_SUCCESS";
export const ADD_SALESMAN_LIST_ERROR = "ADD_SALESMAN_LIST_ERROR";

export const UPDATE_SALESMAN_LOADING = "UPDATE_SALESMAN_LOADING";
export const UPDATE_SALESMAN_SUCCESS = "UPDATE_SALESMAN_SUCCESS";
export const UPDATE_SALESMAN_ERROR = "UPDATE_SALESMAN_ERROR";

export const DELETE_SALESMAN_LOADING = "DELETE_SALESMAN_LOADING";
export const DELETE_SALESMAN_SUCCESS = "DELETE_SALESMAN_SUCCESS";
export const DELETE_SALESMAN_ERROR = "DELETE_SALESMAN_ERROR";

export const CLEAN_SALESMAN_STATE = "CLEAN_SALESMAN_STATE";

// Account
export const GET_ACCOUNT_LOADING = "GET_ACCOUNT_LOADING";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_FILTER_BY = "GET_ACCOUNT_FILTER_BY";

export const GET_ACCOUNT_ID_LOADING = "GET_ACCOUNT_ID_LOADING";
export const GET_ACCOUNT_ID_SUCCESS = "GET_ACCOUNT_ID_SUCCESS";

export const GET_ACCOUNT_SEARCH = "GET_ACCOUNT_SEARCH";

export const CLEAN_ACCOUNT_STATE = "CLEAN_ACCOUNT_STATE";
export const CLEAN_ACCOUNT_ID_STATE = "CLEAN_ACCOUNT_ID_STATE";

// Role Permission
export const GET_ROLE_LOADING = "GET_ROLE_LOADING";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";

export const GET_ROLE_ID_LOADING = "GET_ROLE_ID_LOADING";
export const GET_ROLE_ID_SUCCESS = "GET_ROLE_ID_SUCCESS";
export const GET_ROLE_ID_ERROR = "GET_BRANCH_LIST_ID_ERROR";

export const GET_ROLE_SEARCH_SUCCESS = "GET_ROLE_SEARCH_SUCCESS";

export const CLEAN_ROLE_STATE = "CLEAN_ROLE_STATE";

// Permission
export const GET_PERMISSION_LOADING = "GET_PERMISSION_LOADING";
export const GET_PERMISSION_SUCCESS = "GET_PERMISSION_SUCCESS";

export const GET_PERMISSION_ID_LOADING = "GET_PERMISSION_ID_LOADING";
export const GET_PERMISSION_ID_SUCCESS = "GET_PERMISSION_ID_SUCCESS";
export const GET_PERMISSION_ID_ERROR = "GET_BRANCH_LIST_ID_ERROR";

// History Log
export const GET_HISTORY_LOG_LOADING = "GET_HISTORY_LOG_LOADING";
export const GET_HISTORY_LOG_SUCCESS = "GET_HISTORY_LOG_SUCCESS";
export const GET_HISTORY_LOG_ERROR = "GET_HISTORY_LOG_ERROR";
export const EXPORT_HISTORY_LOG_LOADING = "EXPORT_HISTORY_LOG_LOADING";
export const EXPORT_HISTORY_LOG_SUCCESS = "EXPORT_HISTORY_LOG_SUCCESS";
export const EXPORT_HISTORY_LOG_ERROR = "EXPORT_HISTORY_LOG_ERROR";
export const GET_HISTORY_LOG_MODULE = "GET_HISTORY_LOG_MODULE";
export const GET_HISTORY_LOG_USER = "GET_HISTORY_LOG_USER";
export const GET_HISTORY_LOG_ROLE = "GET_HISTORY_LOG_ROLE";
export const GET_HISTORY_LOG_DATE = "GET_HISTORY_LOG_DATE";
export const CLEAN_HISTORY_LOG_STATE = "CLEAN_HISTORY_LOG_STATE";
export const CLEAN_HISTORY_LOG_FILTER_STATE = "CLEAN_HISTORY_LOG_FILTER_STATE";

// Instant Approval
export const GET_INSTANT_APPROVAL_LOADING = "GET_INSTANT_APPROVAL_LOADING";
export const GET_INSTANT_APPROVAL_SUCCESS = "GET_INSTANT_APPROVAL_SUCCESS";
export const GET_INSTANT_APPROVAL_DETAIL_LOADING =
  "GET_INSTANT_APPROVAL_DETAIL_LOADING";
export const GET_INSTANT_APPROVAL_DETAIL_SUCCESS =
  "GET_INSTANT_APPROVAL_DETAIL_SUCCESS";
export const GET_INSTANT_APPROVAL_IDS = "GET_INSTANT_APPROVAL_IDS";
export const GET_INSTANT_APPROVAL_SEARCH = "GET_INSTANT_APPROVAL_SEARCH";
export const GET_INSTANT_APPROVAL_LEADS_DATE =
  "GET_INSTANT_APPROVAL_LEADS_DATE";
export const GET_INSTANT_APPROVAL_FINCO_DATE =
  "GET_INSTANT_APPROVAL_FINCO_DATE";
export const GET_INSTANT_APPROVAL_VALIDATED_DATE =
  "GET_INSTANT_APPROVAL_VALIDATED_DATE";
export const GET_INSTANT_APPROVAL_EKYC_STATUS =
  "GET_INSTANT_APPROVAL_EKYC_STATUS";
export const GET_INSTANT_APPROVAL_EKYC_PROGRESS =
  "GET_INSTANT_APPROVAL_EKYC_PROGRESS";
export const GET_INSTANT_APPROVAL_FINCO_ENUM =
  "GET_INSTANT_APPROVAL_FINCO_ENUM";
export const GET_INSTANT_APPROVAL_RESULT_ENUM =
  "GET_INSTANT_APPROVAL_RESULT_ENUM";
export const GET_INSTANT_APPROVAL_REJECT_CODE =
  "GET_INSTANT_APPROVAL_REJECT_CODE";
export const GET_INSTANT_APPROVAL_FILTER_ORDER =
  "GET_INSTANT_APPROVAL_FILTER_ORDER";
export const CLEAN_INSTANT_APPROVAL_STATE = "CLEAN_INSTANT_APPROVAL_STATE";
export const CLEAN_INSTANT_APPROVAL_DETAIL_STATE =
  "CLEAN_INSTANT_APPROVAL_DETAIL_STATE";

// Promo
export const GET_PROMO_LOADING = "GET_PROMO_LOADING";
export const GET_PROMO_SUCCESS = "GET_PROMO_SUCCESS";
export const GET_PROMO_ERROR = "GET_PROMO_ERROR";
export const GET_PROMO_SEARCH = "GET_PROMO_SEARCH";
export const GET_PROMO_ID_LOADING = "GET_PROMO_ID_LOADING";
export const GET_PROMO_ID_SUCCESS = "GET_PROMO_ID_SUCCESS";
export const GET_PROMO_ID_ERROR = "GET_PROMO_ID_ERROR";

export const CLEAN_PROMO_STATE = "CLEAN_PROMO_STATE";
export const CLEAN_PROMO_STATE_ID = "CLEAN_PROMO_STATE_ID";

export const ADD_PROMO_LOADING = "ADD_PROMO_LOADING";
export const ADD_PROMO_SUCCESS = "ADD_PROMO_SUCCESS";
export const ADD_PROMO_ERROR = "ADD_PROMO_ERROR";

export const UPDATE_PROMO_LOADING = "UPDATE_PROMO_LOADING";
export const UPDATE_PROMO_SUCCESS = "UPDATE_PROMO_SUCCESS";
export const UPDATE_PROMO_ERROR = "UPDATE_PROMO_ERROR";

export const DELETE_PROMO_LOADING = "DELETE_PROMO_LOADING";
export const DELETE_PROMO_SUCCESS = "DELETE_PROMO_SUCCESS";
export const DELETE_PROMO_ERROR = "DELETE_PROMO_ERROR";

export const CLONE_PROMO_LOADING = "CLONE_PROMO_LOADING";
export const CLONE_PROMO_SUCCESS = "CLONE_PROMO_SUCCESS";
export const CLONE_PROMO_ERROR = "CLONE_PROMO_ERROR";
